// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvyoVIpxMqR0zQjYHT82WYyEVHZclscMg',
    appId: '1:409936587138:web:75249210114ce83d0cc79b',
    messagingSenderId: '409936587138',
    projectId: 'crypto-list-app-259c8',
    authDomain: 'crypto-list-app-259c8.firebaseapp.com',
    storageBucket: 'crypto-list-app-259c8.firebasestorage.app',
    measurementId: 'G-YM1BMC2CK6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn-6C5VuPv4rxASYGrLqMvAybgBlBknag',
    appId: '1:409936587138:android:64176eea9f54981a0cc79b',
    messagingSenderId: '409936587138',
    projectId: 'crypto-list-app-259c8',
    storageBucket: 'crypto-list-app-259c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtThjFXnPC4iuAl0ZHNLjBBswmGYyLdog',
    appId: '1:409936587138:ios:ba4f3ed86a121d100cc79b',
    messagingSenderId: '409936587138',
    projectId: 'crypto-list-app-259c8',
    storageBucket: 'crypto-list-app-259c8.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtThjFXnPC4iuAl0ZHNLjBBswmGYyLdog',
    appId: '1:409936587138:ios:ba4f3ed86a121d100cc79b',
    messagingSenderId: '409936587138',
    projectId: 'crypto-list-app-259c8',
    storageBucket: 'crypto-list-app-259c8.firebasestorage.app',
    iosBundleId: 'com.example.cryptoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvyoVIpxMqR0zQjYHT82WYyEVHZclscMg',
    appId: '1:409936587138:web:289a762c344891290cc79b',
    messagingSenderId: '409936587138',
    projectId: 'crypto-list-app-259c8',
    authDomain: 'crypto-list-app-259c8.firebaseapp.com',
    storageBucket: 'crypto-list-app-259c8.firebasestorage.app',
    measurementId: 'G-N8DQR1MFDV',
  );
}
