// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:crypto_app/repositories/crypto_coins/models/crypto_coin_details_model.dart';
import 'package:crypto_app/repositories/crypto_coins/models/crypto_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailsAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CryptoCoinAdapter());
    registerAdapter(CryptoCoinDetailsAdapter());
  }
}
